feat: addition of more range types
dashevo/grovedb pull request #82
Opened 2022-03-10 16:15 UTC by iammadab

Merk currently supports proofs for:
- key
- range
- range_inclusive

This pr adds:
- range_to
- range_to_inclusive
- range_from
- range_after
- range_after_to
- range_after_to_inclusive
- range_full

2022-03-11 10:15 UTC, fominok approved these changes

2022-03-14 10:31 UTC, QuantumExplorer requested changes

2022-03-14 10:31 UTC, QuantumExplorer commented on merk/src/proofs/query/mod.rs
> +                let left_query = if left_bound < self.tree().key() || left_bound == b"" {
Let's have left and right bounds become Options, it will be a lot more clean.

2022-03-14 19:51 UTC, fominok approved these changes

2022-03-16 12:09 UTC, QuantumExplorer approved these changes

2022-03-16 12:09 UTC, merged